//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventorization.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudienceEquipment
    {
        public int ID { get; set; }
        public int IDAudience { get; set; }
        public int IDEquipment { get; set; }
        public System.DateTime Date { get; set; }
        public int IDEmployee { get; set; }
    
        public virtual Audience Audience { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
