//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventorization.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudienceStudent
    {
        public int ID { get; set; }
        public int IDAudience { get; set; }
        public int IDStudent { get; set; }
        public int WorkPlace { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
    
        public virtual Audience Audience { get; set; }
        public virtual Student Student { get; set; }
    }
}
